name: Add Automerge Label

on:
  pull_request_target:
    types:
      - opened

jobs:
  add-auto-merge-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
