on: [ pull_request_target ]
name: Automerge bot

jobs:
  auto_merge_bot:
    runs-on: ubuntu-latest
    name: EIP Auto-Merge Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: auto-merge-bot
        uses: ethereum/EIP-Bot@master # master
        id: auto-merge-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
          MERGE_ENABLED: false
          CORE_EDITORS: "@MicahZoltu,@lightclient,@axic,@gcolvin,@SamWilsn,@Pandapip1"
          ERC_EDITORS: "@lightclient,@axic,@SamWilsn,@Pandapip1"
          NETWORKING_EDITORS: "@MicahZoltu,@lightclient,@axic,@SamWilsn"
          INTERFACE_EDITORS: "@lightclient,@axic,@SamWilsn"
          META_EDITORS: "@lightclient,@axic,@gcolvin,@SamWilsn"
          INFORMATIONAL_EDITORS: "@lightclient,@axic,@gcolvin,@SamWilsn"
          MAINTAINERS: "@alita-moore,@mryalamanchi"
